config/routes.rb
Gamc::Application.routes.draw do

  resources :cars



  root to: 'cars#index'

end

app/models/body.rb
class Body < ActiveRecord::Base
  attr_accessible :body_type
  has_many :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :colour, :doors, :engine_capacity, :fuel_id, :image, :interior, :make, :manufacture_date, :model, :used, :option_pack, :price, :seats, :sunroof, :transmission, :body_id, :website
  belongs_to :body
  belongs_to :fuel

  def car_to_string
    if used
      new_or_used = "used"
    else
      new_or_used = "new"
    end

    return "#{make} #{model} -- #{self.fuel.fuel_type}, #{transmission.capitalize} -- #{colour.capitalize} with #{interior.capitalize} interior -- #{new_or_used.capitalize}"
  end

end

app/models/fuel.rb
class Fuel < ActiveRecord::Base
  attr_accessible :fuel_type
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.order('price DESC')
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(params[:car])
    @car.save
    redirect_to @car
  end

  def edit
    @car =  Car.find(params[:id])
  end

 def update
    @car = Car.find(params[:id])
    @car.update_attributes(params[:car])
    redirect_to @car
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_car.html.erb
  <%= link_to "£#{car.price.to_i}: #{car.car_to_string}", car %>
  <br>
  <%= link_to 'Edit', edit_car_path(car)%>
  <%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' }%>
  <br>
  <br>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>

<div class="row">
  <div class="span3">
      <%= f.label :make %>
      <%= f.text_field :make, class: 'input_field' %>
      <%= f.label :model %>
      <%= f.text_field :model, class: 'input_field' %>
      <%= f.label :transmission%>
      <%= f.select :transmission, ['automatic', 'manual'], {}, class: 'input_field' %>
      <%= f.label :fuel_id, "Fuel Type" %>
      <%= f.select(:fuel_id, Fuel.all.map {|f| [f.fuel_type, f.id]}, {}, class: 'input_field') %>
      <%= f.label :engine_capacity, "Engine Capacity" %>
      <%= f.text_field :engine_capacity, class: 'input_field'%>
      <%= f.label :colour %>
      <%= f.text_field :colour, class: 'input_field'%>
      <%= f.label :seats %>
      <%= f.text_field :seats, class: 'input_field' %>
      <%= f.label :doors %>
      <%= f.text_field :doors, class: 'input_field' %>
       <%= f.label :price, 'Price' %>
      <%= f.text_field :price, class: 'input_field'%>
  </div>
  <div class="span3">
      <%= f.label :body_id, 'Type' %>
      <%= f.select(:body_id, Body.all.map {|b| [b.body_type, b.id]}, {}, class: 'input_field') %>
      <%= f.label :interior %>
      <%= f.select :interior, ['leather', 'cloth'] , {}, class: 'input_field'%>
      <%= f.label :manufacture_date, 'Date of Manufacturer' %>
      <%= f.text_field :manufacture_date, class: 'input_field' %>
      <%= f.label :used, 'Pre-Owned' %>
      <%= f.select :used, [true, false] , {}, class: 'input_field'%>
      <%= f.label :sunroof, 'Sunroof' %>
      <%= f.select :sunroof, [true, false], {}, class: 'input_field' %>
      <%= f.label :option_pack, 'Option Pack' %>
      <%= f.select :option_pack, [true, false], {}, class: 'input_field' %>
       <%= f.label :image, 'Photo Name' %>
       <%= f.text_field :image, class: 'input_field' %>
       <%= f.label :website, "Manufacturer's Website"  %>
       <%= f.text_field :website, class: 'input_field' %>
      <%= f.submit submit_button_value %>
    </div>
  <%end%>
  <div class="span6">
    <% if @car.persisted? %>
      <%=image_tag @car.image, size: '300x225' %>
    <% end %>
  </div>




</div>

app/views/cars/edit.html.erb
<h2>Edit Car Details</h2>


  <%= render partial: 'form', locals:{submit_button_value: 'Update Car'}%>

app/views/cars/index.html.erb
<h2>Stock List</h2>

<%= render @cars %>

app/views/cars/new.html.erb
<h2>Enter New Car Details</h2>

  <%= render partial: 'form', locals:{submit_button_value: 'Save Car!'}%>

app/views/cars/show.html.erb
<h2>
<%=@car.make %>:
<%= @car.model %>
</h2>
<h3>
<%= @car.engine_capacity %>L,
<%= @car.fuel.fuel_type%>,
<%= @car.transmission.capitalize %>
<br>
£<%= @car.price.to_i %>
<% if @car.used %>
  (used)
<%end%>
</h3>
<p>
Age:
<%= distance_of_time_in_words(Time.now, @car.manufacture_date) %>
</p>
<p>
<%=image_tag @car.image, size: '300x225' %>
</p>
<%=@car.colour.capitalize %>
<%=@car.body.body_type %> with
<%=@car.interior %> interior
</p>
<ul>
  <li>Doors: <%=@car.doors %></li>
  <li>Seats: <%=@car.seats %></li>
  <% if @car.sunroof %>
    <li>Sunroof</li>
  <%end%>
  <% if @car.option_pack %>
    <li>Option Pack</li>
  <%end%>
<li>Date of Manufacture:
<%=@car.manufacture_date %>
</li>
</ul>
<ul>
<li><%= link_to "Manufacturer's Website", @car.website %></li>

  <li><%= link_to 'Edit Car Details', edit_car_path(@car)%></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GAMC</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat+Alternates' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>GA Motor Co. Database App</h1>
  <div class="container">
    <div class="navbar navbar-inverse">
     <div class="navbar-inner">
        <ul class="nav">
          <li><%= link_to('Cars', cars_path) %></li>
          <li><%= link_to('Add New Car', new_car_path)  %></li>
        </ul>
      </div>
    </div>


<%= yield %>
</div>
</body>
</html>